CREATE TABLE patient_guardians(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255),
    CPF VARCHAR(255) UNIQUE,
    RG VARCHAR(255) UNIQUE,
    relationship VARCHAR(25),
    telephone VARCHAR(255) UNIQUE,
    email VARCHAR(255) UNIQUE
)