CREATE TABLE patient_guardians(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100),
    CPF VARCHAR(25) UNIQUE,
    RG VARCHAR(25) UNIQUE,
    relationship VARCHAR(25),
    telephone VARCHAR(25) UNIQUE,
    email VARCHAR(100) UNIQUE
)